### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by adamkarb** [adamkarb/Toastada#2]
* [ ] Support module loading
* [ ] Stylize demo page
* [ ] Provide minified script
